name: Update README with code line count

on:
  push:
    branches:
      - main
  workflow_dispatch:  # ręczne uruchomienie

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Ustal wersję Pythona, np. '3.8' lub '3.9'

    - name: Install dependencies
      run: |
        sudo apt-get install -y cloc
        pip install requests

    - name: Run Python script to update README
      run: |
        python update_readme.py

    - name: Commit and push changes
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "GitHub Actions"
        git add README.md
        git commit -m "Update README with code line count" || echo "No changes to commit"
        git push
